### PR TITLE
Add support for runInTerminal request

### LINKED ISSUE #60: runInTerminal request
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#external-terminal-now-configurable

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #60 
- `externalConsole` is now deprecated
- you can now run your program in the integrated terminal

### CODE REVIEW

**Comment by felixfbecker** [comment]
@weinand Does the testsupport already support the `runInTerminal` request?

**Comment by weinand** [comment]
@felixfbecker not yet. Since this is the first 'reverse' request, it needs some work to provide support for this...

**Comment by felixfbecker** [comment]
@weinand that's unfortunate, I thought that it is implemented in the node debugger would mean you also have tests for that. Cannot merge this because it seems to break the tests completely even though everything works fine.

**Comment by weinand** [comment]
@felixfbecker I do not understand what you mean and why it breaks something.
The `runInTerminal` is implemented in VS Code and node-debug is calling it. The test support is independent from VS Code.

**Comment by felixfbecker** [comment]
runInTerminal is implemented in node-debug. So I assumed you had tests for that in the test suite of the node-debug, so I assumed the testsupport would support it.

The failing tests were a bug on my side though, sorry. I just don't feel very confident merging this as I can't write any tests without testsupport...

**Comment by felixfbecker** [comment]
@weinand Is there a way to highlight the `externalConsole` attribute as deprecated like for the Node debugger? Something like `"deprecated": true` in the JSON schema?

**Comment by zobo** [comment]
Closing in favor of #966

**Pull request closed without merging**
