### PR TITLE
feat: Ignore exceptions based on class name

### PR DESCRIPTION
**Pull request by 8ctopus**
Add ignore exceptions based on class name.

For some reason, mocha tests don't work on my system. It could be that it's not 100% correct, so please be understanding.

### CODE REVIEW

**Comment by zobo** [comment]
Hi!

Thanks for the PR. Exception "breakpoints" are a missing feature for some time, but due to the lack of proper UI support they were not yet implemented.

Interesting approach here, I will look at it more closely.

**Comment by 8ctopus** [comment]
Thank you, I implemented it this way, because when running Laravel, I get tons of exceptions from within the templating engine, the cookie decryption engine and so forth... This change allows to remove the focus from what can safely be ignored.

**Comment by zobo** [comment]
I completely agree this is needed. I just want to be sure before adding new options to `launch.json` that can be hard to remove later if I decide to reimplement things differently.

**Comment by zobo** [comment]
Try running `npm run lint`

**Comment by 8ctopus** [comment]
I ran the linter before implementing the test and didn't check afterwards. It's now fixed. All linter complaints are in parts I didn't touch.

**Comment by 8ctopus** [comment]
Any thoughts?

**Comment by zobo** [comment]
Sorry about the delay, I was away. Will take a look at it again in the next days snd probably just merge.

**Comment by 8ctopus** [comment]
Thank you for the update @zobo , I can't wait to use it.

**Comment by zobo** [comment]
I did some updates and fixes. Decided to rename the setting to  `ignoreExceptions` since we already have `ignore` and `skipFiles`.

**Comment by 8ctopus** [comment]
Awesome, can't wait for the merge. Thank you for looking into it @zobo

**Comment by 8ctopus** [comment]
@zobo When can we expect the merge?

**Comment by zobo** [comment]
Wanted to find a better solution as new cases showed up, but can't get to it now, so I merged it now. Hope it helps. Will revisit and find a better solution.

**Comment by 8ctopus** [comment]
Awesome thank you.

**Pull request merged**
