### PR TITLE
Fix case: XDebug -> Xdebug

### PR DESCRIPTION
**Pull request by angristan**
This is not a troll or anything, I was asking myself what's the correct way to write Xdebug and noticed that "XDebug" is mainly used is this extension. Is it intentional?

Source: https://xdebug.org/

### CODE REVIEW

**Comment by derickr** [comment]
I'd appreciate it if this could be merged :-)

**Comment by chapeupreto** [comment]
Why is it so hard to merge this? 😅

**Comment by zobo** [comment]
Can you rebase this? I'm cleaning up old PRs.

**Comment by angristan** [comment]
Done 👍

**Pull request merged**
