### PR TITLE
fix: fullscreen keybinding conflict with F11 with activeViewlet

### PR DESCRIPTION
**Pull request by shivapoudel**
As the PR title suggests, this fixes key bindings collisions with Fullscreen mode.

### CODE REVIEW

**Comment by zobo** [comment]
Hi! Thanks, will look at it and compare to what VS does with full screen case.

**Comment by shivapoudel** [comment]
@zobo Any updates on this?

**Comment by zobo** [comment]
Will review again asap and check with debug-js...

**Comment by zobo** [comment]
Sorry for not getting to this before. Looks like node debugger does this too, at least for F11  https://github.com/microsoft/vscode-js-debug/blob/1d104b5184736677ab5cc280c70bbd227403850c/src/build/generate-contributions.ts#L1567

This is how the compiled version looks like:
```
    "keybindings": [{
      "command": "extension.node-debug.startWithStopOnEntry",
      "key": "F10",
      "mac": "F10",
      "when": "debugConfigurationType == pwa-node && !inDebugMode || debugConfigurationType == pwa-extensionHost && !inDebugMode || debugConfigurationType == node && !inDebugMode"
    }, {
      "command": "extension.node-debug.startWithStopOnEntry",
      "key": "F11",
      "mac": "F11",
      "when": "debugConfigurationType == pwa-node && !inDebugMode && activeViewlet == workbench.view.debug || debugConfigurationType == pwa-extensionHost && !inDebugMode && activeViewlet == workbench.view.debug || debugConfigurationType == node && !inDebugMode && activeViewlet == workbench.view.debug"
    }],
```

So I'm going to update the code to include the activeViewlet case only for F11 - same thing as Microsoft does, and roll this into the next release I plan to do in a couple of days.

**Pull request merged**
