### PR TITLE
fix: fixed breakpoint and launch initialization order.

### PR DESCRIPTION
**Pull request by zobo**
Request breakpoints only after LaunchRequest is received, but do not return LaunchResponse until DoneRequest is received. This way all breakpoints will be transferred to DAP and properly mapped.

### CODE REVIEW

**Comment by rceci64** [comment]
After this update, the extension does not want to enter into debug mode anymore.
Downgrading to 1.16.1 resolved the problem.

**Comment by zobo** [comment]
Hi! Thanks for the report. Can you give me your php and xdebug version? Are you able to produce any logs by setting  log: true in your launch.json?

**Comment by zobo** [comment]
I was able to reproduce it now. Will look into it asap.

**Comment by zobo** [comment]
Fixed in #608

**Pull request merged**
